name: Test AWS Integration

on:
  push:
    branches: [ master ]

jobs:
  test-aws:
    name: Test AWS credentials
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: List bucket names
      run: |
        aws s3api list-buckets --query "Buckets[].Name"
